services:
  rabbitmq:
    image: rabbitmq:latest
    container_name: rabbitmq
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: admeanie
      RABBITMQ_DEFAULT_PASS: shabi
    configs:
      - source: rabbitmq-plugins
        target: /etc/rabbitmq/enabled_plugins
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq/
      - rabbitmq-plugins:/var/log/rabbitmq/

configs:
  rabbitmq-plugins:
    content: "[rabbitmq_management]."

volumes:
  rabbitmq-data:
    driver: local
  rabbitmq-plugins:
    driver: local